// favourite
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
// cart
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const ADD_ACTIVE_CART_BUTTON = "ADD_ACTIVE_CART_BUTTON";
export const REMOVE_ACTIVE_CART_BUTTON = "REMOVE_ACTIVE_CART_BUTTON";
export const TOGGLE_IS_ADDING_TO_CART = "TOGGLE_IS_ADDING_TO_CART";
// catalog

export const SET_TEA = "SET_TEA";
export const SET_COFFEE = "SET_COFFEE";
export const SET_IS_VISIBLE_CATALOG = "SET_IS_VISIBLE_CATALOG";
export const SET_ACTIVE_TYPE = "SET_ACTIVE_TYPE";
export const SET_ACTIVE_CATALOG = "SET_ACTIVE_CATALOG";
